[package]
name = "stats_browser"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]

[[bin]]
name = "stats_browser"
doc = false

[dependencies]
env_logger = "*"
log = "*"
rustc-serialize = "*"
[dependencies.common] path = "../common"
[dependencies.mio] git = "https://github.com/carllerche/mio"
[dependencies.serverbrowse] path = "../serverbrowse"
[dependencies.time] version = "*" features = ["rustc-serialize"]
