[package]
name = "stats_browser"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]

[[bin]]
name = "stats_browser"
doc = false

[dependencies]
common = { path = "../common/" }
env_logger = "*"
log = "*"
mio = "*"
num = "*"
rustc-serialize = "*"
serverbrowse = { path = "../serverbrowse/" }
time = { version = "*", features = ["rustc-serialize"] }
