[workspace]
members = [
    "common",
    "datafile",
    "demo",
    "downloader",
    "event_loop",
    "gamenet",
    "huffman",
    "huffman/reference",
    "huffman/reference/sys",
    "logger",
    "map",
    "net",
    "packer",
    "render_map",
    "server",
    "serverbrowse",
    "snapshot",
    "socket",
    "stats_browser",
    "teehistorian",
    "tools",
    "wireshark-dissector",
    "world",
    "zlib_minimal",
]
