[package]
name = "huffman"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]

[dependencies]
arrayvec = "*"
common = { path = "../common/" }
itertools = "*"
num = "*"

[dev-dependencies]
huffman-reference = { path = "reference" }
quickcheck = "*"
quickcheck_macros = "*"
