[package]
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
name = "huffman"
version = "0.0.1"

[dependencies]
arrayvec = "0.3.12"
buffer = "0.1.2"
common = { path = "../common/" }
itertools = ">=0.3.0,<0.5.0"

[dev-dependencies]
quickcheck = "0.4.1"
huffman-reference = { path = "reference" }
