[package]
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
name = "huffman"
version = "0.0.1"

[dependencies]
arrayvec = "*"
buffer = "0.1.2"
itertools = "*"
num = "*"

[dependencies.common]
path = "../common/"

[dev-dependencies]
quickcheck = "*"
quickcheck_macros = "*"

[dev-dependencies.huffman-reference]
path = "reference"
