[package]
name = "serverbrowse"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]

[dependencies]
arrayvec = "*"
common = { path = "../common/" }
log = "*"
num = "*"
rustc-serialize = "*"
time = { version = "*", features = ["rustc-serialize"] }
