[package]
name = "serverbrowse"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]

[dependencies]
log = "*"
rustc-serialize = "*"

[dependencies.time]
version = "*"
features = ["rustc-serialize"]

[dependencies.common]
path = "../common/"

[dependencies.mio]
git = "https://github.com/carllerche/mio"
