[package]
name = "serverbrowse"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]

[dependencies]
log = "*"
num = "*"
rustc-serialize = "*"

[dependencies.time]
version = "*"
features = ["rustc-serialize"]

[dependencies.common]
path = "../common/"
