[package]
name = "serverbrowse"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]

[dependencies]
arrayvec = "0.3.12"
common = { path = "../common/" }
env_logger = "0.3.0"
log = "0.3.0"
num = "0.1.27"
rustc-serialize = "0.3.16"
time = { version = "0.1.25", features = ["rustc-serialize"] }
