[package]
name = "serverbrowse"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
arrayvec = "0.3.12"
common = { path = "../common/" }
log = "0.3.0"
logger = { path = "../logger/" }
packer = { path = "../packer/" }
rustc-serialize = "0.3.20"
time = { version = "0.1.25", features = ["rustc-serialize"] }
warn = ">=0.1.0,<0.3.0"
