[package]
name = "world"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
common = { path = "../common/" }
gamenet_teeworlds_0_6 = { path = "../gamenet/teeworlds-0.6/" }
