[package]
name = "snapshot"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]

[dependencies]
common = { path = "../common/" }
num = "0.1.27"
packer = { path = "../packer/" }
warn = "0.1.1"

[dev-dependencies]
buffer = "0.1.5"
