[package]
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
name = "server"
version = "0.0.1"

[dependencies]
arrayvec = "0.3.12"
hexdump = "0.1.0"
itertools = ">=0.3.0,<0.5.0"
log = "0.3.1"
logger = { path = "../logger/" }
net = { path = "../net/" }
socket = { path = "../socket/" }
warn = ">=0.1.1,<0.3.0"
