[package]
name = "huffman-reference"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]

[dependencies]
buffer = "0.1.2"
huffman = { path = ".." }
huffman-reference-sys = { path = "sys" }
libc = "*"
num = "*"
