[package]
name = "downloader"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]

[dependencies]
arrayvec = "0.3.12"
buffer = "0.1.5"
gamenet = { path = "../gamenet/" }
hexdump = "0.1.0"
itertools = "0.4.0"
mio = "0.5.0"
net = { path = "../net/" }
