[package]
name = "datafile"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]

[dependencies]
common = { path = "../common/" }
env_logger = "*"
hexdump = { path = "../hexdump/" }
itertools = "*"
log = "*"
num = "*"
zlib_minimal = { path = "../zlib_minimal" }

[[bin]]
name = "datafile"
doc = false
