[package]
name = "datafile"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]

[dependencies]
common = { path = "../common/" }
logger = { path = "../logger/" }
hexdump = "0.1.0"
itertools = ">=0.3.0,<0.5.0"
log = "0.3.0"
num = "0.1.27"
zlib_minimal = { path = "../zlib_minimal" }

[[bin]]
name = "datafile"
doc = false
