[package]
name = "datafile"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]

[dependencies]
env_logger = "*"
itertools = "*"
log = "*"
num = "*"

[dependencies.common]
path = "../common/"

[dependencies.zlib_minimal]
path = "../zlib_minimal/"

[[bin]]
name = "datafile"
doc = false
