[package]
name = "pre-rfc3243-libtw2-wireshark-dissector-sys"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2021"

[lib]
name = "libtw2_wireshark_dissector_sys"

[dependencies]
