[package]
name = "common"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
arrayvec = "0.3.12"
file_offset = "0.1.0"
num-traits = "0.1.32"
ref_slice = ">=0.1.0,<2.0"

[dev-dependencies]
quickcheck = "0.4.1"
