[package]
name = "hexdump"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]

[dependencies]
arrayvec = "*"
itertools = "*"

[dev-dependencies]
num = "*"
quickcheck = "*"
quickcheck_macros = "*"
