[package]
name = "pre-rfc3243-libtw2-gamenet-teeworlds-0-5"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2021"

[lib]
name = "libtw2_gamenet_teeworlds_0_5"

[dependencies]
arrayvec = "0.5.2"
buffer = "0.1.9"
pre-rfc3243-libtw2-common = { path = "../../common/" }
pre-rfc3243-libtw2-gamenet-common = { path = "../common/" }
pre-rfc3243-libtw2-packer = { path = "../../packer/", features = ["uuid"] }
uuid = "0.8.1"
warn = ">=0.1.1,<0.3.0"
