[package]
name = "map"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]

[dependencies]
common = { path = "../common/" }
datafile = { path = "../datafile/" }
env_logger = "0.3.0"
num = "0.1.27"
