[package]
name = "demo"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
arrayvec = "0.3.22"
buffer = "0.1.7"
common = { path = "../common/" }
huffman = { path = "../huffman/" }
matches = "0.1.1"
packer = { path = "../packer/" }
warn = "0.2.1"
