[package]
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
name = "demo"
version = "0.0.1"

[dependencies]
arrayvec = "0.3.12"
common = { path = "../common/" }
packer = { path = "../packer/" }
warn = "0.2.1"
