[package]
name = "tools"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]

[dependencies]
arrayvec = "0.3.12"
buffer = "0.1.6"
common = { path = "../common/" }
datafile = { path = "../datafile/" }
gamenet = { path = "../gamenet/" }
hexdump = "0.1.0"
log = "0.3.1"
logger = { path = "../logger/" }
map = { path = "../map/" }
ndarray = "0.6.1"
net = { path = "../net/" }
packer = { path = "../packer/" }
serverbrowse = { path = "../serverbrowse/" }
warn = ">=0.1.1,<0.3.0"
