[package]
name = "tools"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
arrayvec = "0.3.12"
buffer = "0.1.6"
common = { path = "../common/" }
clap = "2.23.1"
datafile = { path = "../datafile/" }
demo = { path = "../demo/" }
gamenet = { path = "../gamenet/" }
hexdump = "0.1.0"
log = "0.3.1"
logger = { path = "../logger/" }
map = { path = "../map/" }
net = { path = "../net/" }
packer = { path = "../packer/" }
rmp = "0.8.5"
serverbrowse = { path = "../serverbrowse/" }
warn = "0.2.2"
