[package]
name = "net"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]

[dependencies]
arrayvec = "*"
common = { path = "../common/" }
huffman = { path = "../huffman/" }

[dev-dependencies]
quickcheck = "*"
quickcheck_macros = "*"
