[package]
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
name = "net"
version = "0.0.1"

[dependencies]
arrayvec = "*"
buffer = "0.1.4"
num = "*"

[dependencies.common]
path = "../common/"

[dependencies.huffman]
path = "../huffman/"

[dev-dependencies]
quickcheck = "*"
quickcheck_macros = "*"
