[package]
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
name = "net"
version = "0.0.1"

[dependencies]
arrayvec = "0.3.12"
buffer = "0.1.5"
common = { path = "../common/" }
huffman = { path = "../huffman/" }
num = "0.1.27"
void = ">=0.0.4,<2.0.0"

[dev-dependencies]
hexdump = { path = "../hexdump/" }
itertools = ">=0.3.0,<0.5.0"
quickcheck = "*"
quickcheck_macros = "*"
