[package]
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
name = "net"
version = "0.0.1"

[dependencies]
arrayvec = "0.3.12"
assert_matches = "1.0.1"
buffer = "0.1.5"
common = { path = "../common/" }
huffman = { path = "../huffman/" }
linear-map = "1.0.0"
num = "0.1.27"
void = ">=0.0.4,<2.0.0"
warn = ">=0.1.1,<0.3.0"

quickcheck = { version = "0.2.27", optional = true }
quickcheck_macros = { version = "0.2.26", optional = true }

[dev-dependencies]
hexdump = "0.1.0"
itertools = ">=0.3.0,<0.5.0"

[features]
nightly-test = ["quickcheck", "quickcheck_macros"]
